version: "3.9"
services:
  tauvservice:
    build: .
    image: tauvcontainer:orin-base
    volumes:
      - /dev:/dev
      - /tm.X11-unix/:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - /home/tartanauv/shared:/shared
      - /home/tartanauv/data:/data
    environment:
      XAUTHORITY: /tmp/.docker.xauth
    network_mode: "host"
    privileged: true
    runtime: nvidia
